#!/bin/sh
err_report() {
    echo "Build.sh Failed"
}
trap 'err_report' ERR
. ./config
for PROJECT in $PROJECTS; do
  (cd $PROJECT && DESTDIR="$SYSROOT" make install-headers)
done
for PROJECT in $PROJECTS; do
  (cd $PROJECT && DESTDIR="$SYSROOT" make install)
done
